esphome:
  name: mix
  friendly_name: Mixer
  min_version: 2024.11.0
  name_add_mac_suffix: false
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.flash_mode: dio
    board_upload.maximum_size: 16777216
  project: 
    name: esphome.web
    version: dev
  includes:
    - mix_tools.h

esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  flash_size: 16MB
  framework:
    type: esp-idf
    version: recommended

psram:
  mode: octal
  speed: 80MHz

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
# api:

ota:
  - platform: esphome
    id: my_ota
    password: !secret ota_password

wifi:
  enable_rrm: true
  fast_connect: true
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Mixer Fallback Hotspot"
    password: !secret fallback_password


web_server:
  port: 80

captive_portal:

sensor:
  - platform: adc
    id: vref
    internal: true
    pin: GPIO8
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s0_v
    internal: true
    pin: GPIO1
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s1_v
    internal: true
    pin: GPIO2
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s2_v
    internal: true
    pin: GPIO4
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s3_v
    internal: true
    pin: GPIO5
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s4_v
    internal: true
    pin: GPIO6
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: adc
    id: s5_v
    internal: true
    pin: GPIO7
    update_interval: 1ms
    samples: 128
    raw: true

  - platform: template
    id: pot0
    name: "0"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s0_v).state), (uint16_t)(id(vref).state));

  - platform: template
    id: pot1
    name: "1"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s1_v).state), (uint16_t)(id(vref).state));

  - platform: template
    id: pot2
    name: "2"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s2_v).state), (uint16_t)(id(vref).state));

  - platform: template
    id: pot3
    name: "3"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s3_v).state), (uint16_t)(id(vref).state));

  - platform: template
    id: pot4
    name: "4"
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s4_v).state), (uint16_t)(id(vref).state));

  - platform: template
    id: pot5
    name: "5"
    
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: 1ms
    lambda: |-
      return (float) mixer_math((uint16_t)(id(s5_v).state), (uint16_t)(id(vref).state));
